keys:
  - &lytharn_mewx age1h4hrxfrd9dyegqjmvgdw0zdenkpfgpavw57q5djcf2l8lg3e3vtse7npwm
  - &machine_mewx age1fyuudaqszs4yk6r7w77aszp0ynsget3h34gqh7zkpv4hqqul6dkqlyhrsn
  - &machine_serx age1c6hftmen4jkst37q3e9gq9uqr6etcwsdvllk3gdafuayxhzz7v2smrhsn2
creation_rules:
  # This is a regex, so it could look like this
  # - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
  - path_regex: secrets/mewx/secrets.yaml$
    key_groups:
    - age:
      - *lytharn_mewx
      - *machine_mewx
  - path_regex: secrets/serx/secrets.yaml$
    key_groups:
    - age:
      - *lytharn_mewx
      - *machine_serx
